---
title: "Assignment 4"
author: "Brett Davidoff"
date: "5/2/2022"
output: html_document
---


```{r echo=FALSE}
# load required packages
library(ggplot2)
library(dplyr)
library(corrplot)
library(MASS)
library(caret)
library(RCurl)
library(pROC)
library(RCurl)
library(haven)
library(car)
```

```{r}
# Load data
test_df = read.csv("https://raw.githubusercontent.com/BDavidoff/Data_621/main/insurance-evaluation-data.csv")
train_df = read.csv("https://raw.githubusercontent.com/BDavidoff/Data_621/main/insurance_training_data.csv")
```
## Data Exploration & Preparation

```{r}
#Check data
summary(train_df)
summary(test_df)
str(train_df)
```


```{r}
#Check TARGET_FLAG and other numerical variables.
par(mfrow=c(1,2))
# target vs age and car_age
boxplot(AGE ~ TARGET_FLAG, train_df, 
        main="Target vs Age",
        xlab="Target",
        ylab="Age") 
boxplot(CAR_AGE ~ TARGET_FLAG, train_df, 
        main="Target vs Car Age",
        xlab="Target",
        ylab="Car Age")
```


```{r}
#distribution of numerical variables.
histogram = hist(train_df$AGE, main="Histogram of Age", xlab="Age")
text(histogram$mids,histogram$counts,labels=histogram$counts)
```

```{r}
h <- hist(train_df$MVR_PTS)
text(h$mids,h$counts,labels=h$counts)
```


```{r}
make_numeric = function(input) {
  return(as.numeric(sub(",", "", sub("\\$", "", input))))
}
train_df = as.tbl(train_df) %>% 
  mutate_at(c("INCOME","HOME_VAL","BLUEBOOK","OLDCLAIM"), make_numeric)
#check data
summary(train_df)
```

```{r}
#clean data
train_df$AGE[is.na(train_df$AGE)] = mean(train_df$AGE, na.rm=TRUE)
train_df$YOJ[is.na(train_df$YOJ)] = mean(train_df$YOJ, na.rm=TRUE)
train_df$HOME_VAL[is.na(train_df$HOME_VAL)]= mean(train_df$HOME_VAL, na.rm=TRUE)
train_df$CAR_AGE[is.na(train_df$CAR_AGE)] = mean(train_df$CAR_AGE, na.rm=TRUE)
train_df$INCOME[is.na(train_df$INCOME)] = mean(train_df$INCOME, na.rm=TRUE)

#complete cases
train_df = train_df[complete.cases(train_df),]
train_df2 = train_df[-c(1)]
```


```{r}
train_amt_df = subset(train_df, TARGET_AMT > 0)
summary(train_amt_df$TARGET_FLAG)
```

Binary Logistic Regression Models
```{r}
#preliminary exploration with one predictor
model1 = glm(formula = TARGET_FLAG ~ AGE, family = binomial(), data = train_df2)
summary(model1)
```

```{r}
#all predictor variables
model2 = glm(formula = TARGET_FLAG ~ .- TARGET_AMT, family = binomial(), data = train_df2)
summary(model2)
```


```{r}
step_BLR = stepAIC(model2)
summary(model2)
```

```{r}
# model 3, selected significant variables from model 2
model3 = glm(formula = TARGET_FLAG ~ 
  KIDSDRIV + INCOME      + PARENT1 + 
  HOME_VAL + MSTATUS     + EDUCATION + 
  JOB      + TRAVTIME    + CAR_USE + 
  BLUEBOOK + TIF         + CAR_TYPE + 
  OLDCLAIM + CLM_FREQ    + REVOKED + 
  MVR_PTS  + URBANICITY, 
  family = binomial(), data = train_df2)
summary(model3)
```
### 2) Multiple Linear Regression

```{r}
#model1, all predictors
lm1 = lm(TARGET_AMT ~ ., data = train_df2)
summary(lm1)
```

```{r}
step = stepAIC(lm1, direction="both")
```


```{r}
#model2, selected
lm2 = lm(TARGET_AMT ~ 
  TARGET_FLAG + PARENT1 + SEX     + 
  BLUEBOOK    + REVOKED + MVR_PTS + 
  CAR_AGE,
  data = train_df2)
summary(lm2)
```
```{r}
car::vif(model2)
```

```{r}
#Using model2 because of the lower AIC out of the three models
test_df$AGE[is.na(test_df$AGE)]           = mean(test_df$AGE, na.rm=TRUE)
test_df$YOJ[is.na(test_df$YOJ)]           = mean(test_df$YOJ, na.rm=TRUE)
test_df$HOME_VAL[is.na(test_df$HOME_VAL)] = mean(test_df$HOME_VAL, na.rm=TRUE)
test_df$CAR_AGE[is.na(test_df$CAR_AGE)]   = mean(test_df$CAR_AGE, na.rm=TRUE)
test_df$INCOME[is.na(test_df$INCOME)]     = mean(test_df$INCOME, na.rm=TRUE)

#complete cases
test_df = test_df[complete.cases(test_df),]
test_df2 = test_df
test_df2 = test_df2[-c(1)]

numeric = function(input) {
  out = sub("\\$", "", input)
  out = as.numeric(sub(",", "", out))
  return(out)
}
test_df2 = as.tbl(test_df2) %>% 
  mutate_at(c("INCOME","HOME_VAL","BLUEBOOK","OLDCLAIM"),
            numeric)
```


```{r}
# step_BLR prediction on test
test_df = test_df[-c(1)]
test_preds_BLR = round(predict(model2, newdata=test_df, type='response'))
test_df$TARGET_FLAG = test_preds_BLR
test_preds_MLR = predict(lm2, newdata=test_df)
test_df$TARGET_AMT = test_preds_MLR
# write out evaluation data with predictions
write.csv(test_df2, 'eval_with_preds.csv')
```